[tools]
go = 'latest'
ghq = 'latest'
deno = 'latest'
fzf = 'latest'
gh = 'latest'
neovim = "nightly"
node = 'latest'
rust = 'latest'
tmux = 'latest'
"npm:@anthropic-ai/claude-code" = 'latest'
eza = "latest"
lazygit = "latest"
ripgrep = "latest"
direnv = "latest"
poetry = "latest"
yq = "latest"
"npm:@google/gemini-cli" = "latest"
mysqldef = "latest"
fd = "latest"
python = "latest"
"pipx:mcp-obsidian" = "latest"
duckdb = "latest"
uv = "latest"
gcloud = "latest"
bun = "latest"
bat = "latest"
delta = "latest"
"pipx:pyrefly" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["terraform"]
